name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Install Gradle 8.14.3 (system)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14.3
          cache-disabled: true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release APK
        run: gradle assembleRelease --build-cache

      - name: Set short SHA (7 chars)
        id: set_sha
        run: |
          # lấy 7 ký tự đầu của GITHUB_SHA và export nó làm output của step
          echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          
      - name: Rename APK with short SHA
        run: |
          short_sha=${{ steps.set_sha.outputs.short_sha }}
          src="app/build/outputs/apk/release/app-release.apk"
          dst="app/build/outputs/apk/release/app-release-${short_sha}.apk"
          echo "Renaming $src -> $dst"
          if [ -f "$src" ]; then
            mv "$src" "$dst"
          else
            echo "ERROR: APK not found at $src"
            ls -la app/build/outputs/apk/release || true
            exit 1
          fi

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release-${{ steps.set_sha.outputs.short_sha }}
          path: app/build/outputs/apk/release/app-release-*.apk
          if-no-files-found: error
