name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Prepare Artifact
        run: |
          sha_short=${{ steps.vars.outputs.sha_short }}
          # Find and rename the original jar
          original_jar_path=$(find build/libs -name "*.jar")
          renamed_jar_path="build/libs/Fly-mod-$sha_short.jar"
          mv "$original_jar_path" "$renamed_jar_path"
          # Create the zip file containing the renamed jar
          zip -j "Fly-mod-$sha_short.zip" "$renamed_jar_path"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fly-mod-${{ steps.vars.outputs.sha_short }}
          path: Fly-mod-${{ steps.vars.outputs.sha_short }}.zip
          if-no-files-found: error
